import { Component, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-cli-demo',
  templateUrl: './cli-demo.html',
  styleUrl: './cli-demo.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CliDemo {
  vitestCode = `// angular.json ,  Vitest configuration options
{
  "projects": {
    "my-app": {
      "architect": {
        "test": {
          "builder": "@angular/build:unit-test",
          "options": {
            "tsConfig": "tsconfig.spec.json",
            "isolate": true,          // Run each test file in isolation
            "quiet": true,            // Suppress build output noise
            "coverage": {
              "enabled": true,
              "provider": "istanbul"   // Istanbul coverage support
            }
          }
        }
      }
    }
  }
}`;

  aiConfigCode = `# Run the schematic — it prompts you to pick AI tools:
$ ng generate ai-config

# Available tools:
# ┌─────────────────┬────────────────────────────────────────────┐
# │ claude-code     │ AGENTS.md + Angular MCP server config      │
# │ cursor          │ AGENTS.md + Angular MCP server config      │
# │ gemini-cli      │ GEMINI.md + Angular MCP server config      │
# │ open-ai-codex   │ AGENTS.md + Angular MCP server config      │
# │ vscode          │ AGENTS.md + Angular MCP server config      │
# └─────────────────┴────────────────────────────────────────────┘

# Example: configure for VS Code + Claude Code
$ ng generate ai-config --tool vscode --tool claude-code`;

  mcpConfigCode = `// .vscode/mcp.json — generated by ng generate ai-config --tool vscode
{
  // For more information, visit: https://angular.dev/ai/mcp
  "servers": {
    "angular-cli": {
      "command": "npx",
      "args": ["-y", "@angular/cli", "mcp"]
    }
  }
}

// CLAUDE.toml — generated by ng generate ai-config --tool claude-code
[mcp_servers.angular-cli]
command = "npx"
args = ["-y", "@angular/cli", "mcp"]`;

  mcpServerCode = `# The Angular MCP server provides tools for AI agents:
$ npx @angular/cli mcp

# What the MCP server exposes to AI agents:
# → Project structure discovery (list_projects)
# → Angular best practices (get_best_practices)
# → Official documentation search (search_documentation)
# → Code examples for modern features (find_examples)

# New projects (ng new) automatically include .vscode/mcp.json!`;

  migrationRows = [
    { old: 'Node.js v20', new: 'Node.js v22.22.0+ / v24.13.1+', badge: 'removed' },
    { old: '@angular-devkit/architect-cli', new: '@angular-devkit/architect', badge: 'removed' },
    { old: 'Jest / Web Test Runner builders', new: 'Vitest (@angular/build:unit-test)', badge: 'removed' },
    { old: 'experimentalPlatform', new: 'platform (stabilized)', badge: 'changed' },
    { old: 'Webpack builders', new: '@angular/build', badge: 'changed' },
    { old: 'CommonEngine (from @angular/ssr)', new: 'AngularNodeAppEngine / AngularAppEngine', badge: 'changed' },
    { old: '@ngtools/webpack', new: '@angular/build', badge: 'removed' },
  ];
}
